### ISSUE TITLE
QobuzDownloaderX stopped working for a few days .

### ISSUE THREAD

**Issue by Boris7y** [ImAiiR/QobuzDownloaderX#103]
Enters the system , starts downloading and immediately cuts off . Windows 7 is installed . The program is included in the antivirus exceptions, tls 1.2 is enabled.
![Снимок 2](https://user-images.githubusercontent.com/94806413/142779389-734d4131-f338-412b-bba8-c14c64fc8c40.PNG)

**Comment by ThinBucket82549** [comment]
Qobuz Updated their api. So Just Wait a bit

**Comment by Wim1975** [comment]
There are other issues ... 
1. artist links are no longer working since a month ago. 
2. the extra information in the album title between '(' and ')' is no longer included. 
This results in different versions of albums being downloaded in folders having the exact same name.
3. there are no options to change the download folder structure format
4. Not sure if this project is still being worked on... as there was no reaction, even after buying 5 coffees.
