### ISSUE TITLE
1.0.0.2 File Saving Questions

### ISSUE THREAD

**Issue by pd2020pd** [ImAiiR/QobuzDownloaderX#160]
Can you pls advise how to:
1- Save files in a directory under the title with the quality (example directory - "FLAC (24bit-48kHz)") 
2-How to add a hyphen between the track# and the track title (example 01 - Title)

I got used to these settings on the previous version.

Thanks for the update!

**Comment by vad62** [comment]
1. Instead of the directory, which is not convenient, add the name of the album to the end of the variable to the template 
%ArtistName%-%AlbumTitle%[%Year%]**[%FormatWithHiResQuality%]**
and each album will be signed:
_Lewis Capaldi-How I'm Feeling Now[2023][FLAC (24bit-48kHz)]_
2. In the template of the name of the track between the variables, you need to write a hyphen:
%TrackNumber%-%TrackArtist%-%TrackTitle%
_01-Lewis Capaldi-How I'm Feeling Now.flac_

3. For the creator of the program, the interface when downloading was more informative, you can adjust the new one:

<img width="201" alt="Снимок экрана 2024-10-18 в 12 35 36" src="https://github.com/user-attachments/assets/9ecea69c-4124-44f6-8829-c74e78900e5e">

**Comment by pd2020pd** [comment]
Thanks - perfect.
