### ISSUE TITLE
Future Request: Bulk Downloads

### ISSUE THREAD

**Issue by Gamer4Life2020** [ImAiiR/QobuzDownloaderX#30]
If not already a way and I don't know how. Would there be any to do bulk downloads via a TXT file or to past in several links? As, I know I can do artists but don't always want everything of if there are several artist with like names I don't want. Like qo-dl I can paste several links and it will do each until done. 
Also, if not to hard to implement could releasetype be added to the tags? As it would help with sorting and not have to mark each single, ep, live etc.

Thanks for keeping this going as Sorrow446 took down qo-dl.

**Comment by ImAiiR** [comment]
For bulk downloads, you can add the releases you want to download to your favorites, and then use the link to your favorites to download all of them together. This only works for favorites full releases at the moment, so won't work for favorites that are individual tracks. I'll see what I can do about adding bulk support through text file, or separation with a ";" in the URL textbox between links.

As for release type tags, that shouldn't be too difficult, Qobuz does return that in their JSON responses, so I should be able to add that fairly easily. Though I have noticed sometimes it returns as "null"in the response, so that'll be an issue I can't get around.

**Comment by Gamer4Life2020** [comment]
Awesome, Thanks.

**Comment by ImAiiR** [comment]
Not bulk downloads yet, but I've just added embedded release type tags in the latest version. Hopefully it works out for you.
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.16

**Comment by Gamer4Life2020** [comment]
Awesome, Thanks.
