### ISSUE TITLE
with last version login error

### ISSUE THREAD

**Issue by 1claudiobruno** [ImAiiR/QobuzDownloaderX#33]
Hi, i tried to login in 0.9.9.16, and can't login, tried alternative method too...
here the log:

System.Net.WebException: Errore del server remoto: (401) Non autorizzato.
   in System.Net.HttpWebRequest.GetResponse()
   in QobuzDownloaderX.LoginFrm.loginBG_DoWork(Object sender, DoWorkEventArgs e)

**Comment by ImAiiR** [comment]
Tested the same version on my end, logging in fine, so I believe it's happening on your end. So let's try the basics first and see if anything fixes it.

- Make sure your PC date & time is set correctly.
- Make 100% sure that the information you're trying to log in with is correct.
- If you've been using the alternative method for logging in, and it just recently stopped working, you may want to get new values and try again.
- If connected to a VPN, try switching to a new server, or disconnect entirely to see if that is the issue.
- I don't think this would do anything, but sometimes it just works, restart your computer.

Whatever happens when trying these things, let me know, especially if you get a new error message or the issue gets fixed.
